import type { ThemeName } from "./types.ts";

export interface ThemeConfig { name: ThemeName; label: string; description: string; sceneOrnament: string; dropcap: boolean; chapterLabel: string; previewFont: string; previewHeadingFont: string; previewAccent: string; previewPaper: string; }

export const THEMES: Record<ThemeName, ThemeConfig> = {
  modern: { name: "modern", label: "Modern", description: "Clean sans-serif headings, generous spacing, minimalist scene breaks.", sceneOrnament: "•   •   •", dropcap: false, chapterLabel: "CHAPTER 01", previewFont: "Arial, sans-serif", previewHeadingFont: "Arial, sans-serif", previewAccent: "#20262c", previewPaper: "#ffffff" },
  decorative: { name: "decorative", label: "Decorative", description: "Serif body with drop caps and a floral ornament between scenes.", sceneOrnament: "❧", dropcap: true, chapterLabel: "Chapter One", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Baskerville, Georgia, serif", previewAccent: "#9a6a32", previewPaper: "#fffdf7" },
  literary: { name: "literary", label: "Literary", description: "Quiet old-style typography with a restrained offset opening.", sceneOrnament: "⁂", dropcap: true, chapterLabel: "CHAPTER ONE", previewFont: "Garamond, Georgia, serif", previewHeadingFont: "Garamond, Georgia, serif", previewAccent: "#493f36", previewPaper: "#fbf8f0" },
  editorial: { name: "editorial", label: "Editorial", description: "High-contrast magazine typography with crisp rules and block openings.", sceneOrnament: "◆", dropcap: false, chapterLabel: "01 / CHAPTER", previewFont: "Georgia, serif", previewHeadingFont: "Arial, sans-serif", previewAccent: "#a52d2d", previewPaper: "#fff" },
  heritage: { name: "heritage", label: "Heritage", description: "Formal book typography with roman numerals and engraved ornaments.", sceneOrnament: "❦", dropcap: true, chapterLabel: "CHAPTER I", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Baskerville, Georgia, serif", previewAccent: "#6f4930", previewPaper: "#faf5e8" },
  scholar: { name: "scholar", label: "Scholar", description: "Measured academic styling with clear hierarchy and compact notes.", sceneOrnament: "§", dropcap: false, chapterLabel: "CHAPTER 1", previewFont: "Cambria, Georgia, serif", previewHeadingFont: "Cambria, Georgia, serif", previewAccent: "#263d56", previewPaper: "#fcfcfb" },
  folio: { name: "folio", label: "Folio", description: "Folio's balanced signature style: warm serif text and precise openings.", sceneOrnament: "◇", dropcap: true, chapterLabel: "ONE", previewFont: "Palatino, Georgia, serif", previewHeadingFont: "Avenir, Arial, sans-serif", previewAccent: "#856744", previewPaper: "#fcfaf5" },
  ivory: { name: "ivory", label: "Ivory", description: "Airy cream-page design with delicate italics and generous margins.", sceneOrnament: "· · ·", dropcap: false, chapterLabel: "Chapter One", previewFont: "Garamond, Georgia, serif", previewHeadingFont: "Garamond, Georgia, serif", previewAccent: "#8c765b", previewPaper: "#fffaf0" },
  nocturne: { name: "nocturne", label: "Nocturne", description: "Elegant dark-ink drama with moonlike ornaments and narrow titles.", sceneOrnament: "☾", dropcap: true, chapterLabel: "I", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Didot, Georgia, serif", previewAccent: "#39445f", previewPaper: "#f5f5f3" },
  cloister: { name: "cloister", label: "Cloister", description: "Illuminated monastic bookwork: rubricated initials, blue-red ruling and manuscript page rhythm without baked-in pseudo-Latin labels.", sceneOrnament: "✠", dropcap: true, chapterLabel: "I", previewFont: "Libre Caslon Text, serif", previewHeadingFont: "Cinzel, serif", previewAccent: "#8f3129", previewPaper: "#f0e2bd" },
  blackletter: { name: "blackletter", label: "Blackletter", description: "Gothic display openings paired with a highly readable serif body.", sceneOrnament: "❧", dropcap: true, chapterLabel: "I", previewFont: "Georgia, serif", previewHeadingFont: "UnifrakturCook, Georgia, serif", previewAccent: "#251d1a", previewPaper: "#f4ecda" },
  parchment: { name: "parchment", label: "Parchment", description: "Warm historical pages with ink-brown type and hand-set character.", sceneOrnament: "~ ✦ ~", dropcap: true, chapterLabel: "The First Chapter", previewFont: "Palatino, Georgia, serif", previewHeadingFont: "Palatino, Georgia, serif", previewAccent: "#8a4f2d", previewPaper: "#f6ead0" },
  atlas: { name: "atlas", label: "Atlas", description: "Expedition-journal styling with utilitarian sans headings and maplike rules.", sceneOrnament: "— ◉ —", dropcap: false, chapterLabel: "FIELD 01", previewFont: "Georgia, serif", previewHeadingFont: "Arial Narrow, Arial, sans-serif", previewAccent: "#31594e", previewPaper: "#f4f2e8" },
  stanza: { name: "stanza", label: "Stanza", description: "Poetry-minded proportions, ragged text and lyrical centered openings.", sceneOrnament: "⁕", dropcap: false, chapterLabel: "I", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Baskerville, Georgia, serif", previewAccent: "#6f5573", previewPaper: "#fff" },
  aubade: { name: "aubade", label: "Aubade", description: "Bright morning palette with graceful italic headings and open leading.", sceneOrnament: "✺", dropcap: true, chapterLabel: "I", previewFont: "Palatino, Georgia, serif", previewHeadingFont: "Baskerville, Georgia, serif", previewAccent: "#c47c36", previewPaper: "#fffaf1" },
  ember: { name: "ember", label: "Ember", description: "Forceful rust accents and muscular chapter openings for genre fiction.", sceneOrnament: "◆", dropcap: true, chapterLabel: "CHAPTER ONE", previewFont: "Georgia, serif", previewHeadingFont: "Arial Black, Arial, sans-serif", previewAccent: "#a33f25", previewPaper: "#fbf7f1" },
  cinder: { name: "cinder", label: "Cinder", description: "Cool monochrome minimalism with condensed headings and hard scene cuts.", sceneOrnament: "■", dropcap: false, chapterLabel: "01", previewFont: "Cambria, Georgia, serif", previewHeadingFont: "Arial Narrow, Arial, sans-serif", previewAccent: "#4b5055", previewPaper: "#f5f5f4" },
  solstice: { name: "solstice", label: "Solstice", description: "Geometric seasonal ornament, wide tracking and ceremonial openings.", sceneOrnament: "✦", dropcap: true, chapterLabel: "I", previewFont: "Georgia, serif", previewHeadingFont: "Avenir, Arial, sans-serif", previewAccent: "#526b78", previewPaper: "#f8faf8" },
  timber: { name: "timber", label: "Timber", description: "Earthy, sturdy typography with slab-like headings and practical spacing.", sceneOrnament: "◆ ◆ ◆", dropcap: false, chapterLabel: "CHAPTER 1", previewFont: "Charter, Georgia, serif", previewHeadingFont: "Rockwell, Georgia, serif", previewAccent: "#59452f", previewPaper: "#f7f1e5" },
  obsidian: { name: "obsidian", label: "Obsidian", description: "Razor-black fantasy typography with a faceted ceremonial opening.", sceneOrnament: "◆", dropcap: true, chapterLabel: "I", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Didot, Georgia, serif", previewAccent: "#17171b", previewPaper: "#f1f0ed" },
  bloodmoon: { name: "bloodmoon", label: "Blood Moon", description: "Crimson lunar accents and dramatic high-contrast gothic chapter pages.", sceneOrnament: "◉", dropcap: true, chapterLabel: "MOON I", previewFont: "Garamond, Georgia, serif", previewHeadingFont: "Bodoni MT, Didot, Georgia, serif", previewAccent: "#771f26", previewPaper: "#f8f1ec" },
  grimoire: { name: "grimoire", label: "Grimoire", description: "Arcane manuscript proportions, double rules and sigil-like ornaments.", sceneOrnament: "☙ ❦ ❧", dropcap: true, chapterLabel: "I", previewFont: "Palatino, Georgia, serif", previewHeadingFont: "Book Antiqua, Palatino, serif", previewAccent: "#4b315d", previewPaper: "#f4eddc" },
  cathedral: { name: "cathedral", label: "Cathedral", description: "Gothic arched chapter openings with stone-blue rules, blackletter display type and structural Roman numbering.", sceneOrnament: "✠", dropcap: true, chapterLabel: "I", previewFont: "Baskerville, Georgia, serif", previewHeadingFont: "Old English Text MT, Georgia, serif", previewAccent: "#293543", previewPaper: "#f3f1e9" },
  necropolis: { name: "necropolis", label: "Necropolis", description: "Monumental Roman capitals and stone-cut rules for dark epic fiction, with numbering kept purely structural.", sceneOrnament: "— ◈ —", dropcap: false, chapterLabel: "I", previewFont: "Cambria, Georgia, serif", previewHeadingFont: "Cinzel, Times New Roman, serif", previewAccent: "#44464b", previewPaper: "#f0efeb" },
  wyrmwood: { name: "wyrmwood", label: "Wyrmwood", description: "Woodcut-inspired forest fantasy with an asymmetric storybook opening.", sceneOrnament: "❧", dropcap: true, chapterLabel: "TALE ONE", previewFont: "Charter, Georgia, serif", previewHeadingFont: "Palatino, Georgia, serif", previewAccent: "#35503a", previewPaper: "#f2efe2" },
  runestone: { name: "runestone", label: "Runestone", description: "Angular Nordic display type and carved dividers with a clean reading face.", sceneOrnament: "◇ ◆ ◇", dropcap: false, chapterLabel: "RUNE 01", previewFont: "Georgia, serif", previewHeadingFont: "Copperplate, Arial Narrow, sans-serif", previewAccent: "#405868", previewPaper: "#f2f5f3" },
  witchlight: { name: "witchlight", label: "Witchlight", description: "Elegant occult fantasy with violet ink, star points and whispered italics.", sceneOrnament: "✦", dropcap: true, chapterLabel: "I", previewFont: "Garamond, Georgia, serif", previewHeadingFont: "Baskerville, Georgia, serif", previewAccent: "#60446f", previewPaper: "#f7f3f6" },
  ironbound: { name: "ironbound", label: "Ironbound", description: "Heavy forged headings, boxed numerals and disciplined military-fantasy rhythm.", sceneOrnament: "■", dropcap: false, chapterLabel: "01", previewFont: "Charter, Georgia, serif", previewHeadingFont: "Rockwell, Arial Black, serif", previewAccent: "#333b3d", previewPaper: "#f4f1e9" },
  "event-horizon": { name: "event-horizon", label: "Event Horizon", description: "Space-opera scale with orbital rules, compressed display type and a severe cinematic opening.", sceneOrnament: "○  ·  ○", dropcap: false, chapterLabel: "ORBIT 01", previewFont: "\"Folio Source Serif 4\", Georgia, serif", previewHeadingFont: "\"Folio Barlow Condensed\", Arial, sans-serif", previewAccent: "#263c5a", previewPaper: "#f5f7fa" },
  signal: { name: "signal", label: "Signal", description: "Hard sci-fi restraint: technical indexing, clean hierarchy and disciplined scientific typography.", sceneOrnament: "—  +  —", dropcap: false, chapterLabel: "SIGNAL 01", previewFont: "\"Folio Newsreader\", Georgia, serif", previewHeadingFont: "\"Folio Source Sans 3\", Arial, sans-serif", previewAccent: "#285b63", previewPaper: "#f6f8f7" },
  nova: { name: "nova", label: "Nova", description: "Literary speculative fiction with luminous Bodoni openings and quiet, expansive page rhythm.", sceneOrnament: "✧", dropcap: true, chapterLabel: "I", previewFont: "\"Folio Newsreader\", Georgia, serif", previewHeadingFont: "\"Folio Bodoni Moda\", Georgia, serif", previewAccent: "#5962a5", previewPaper: "#fbfaf7" },
  redline: { name: "redline", label: "Redline", description: "Fast contemporary thriller typography with compressed headings, hard rules and urgent chapter numbers.", sceneOrnament: "━", dropcap: false, chapterLabel: "01", previewFont: "\"Folio Vollkorn\", Georgia, serif", previewHeadingFont: "\"Folio Barlow Condensed\", Arial, sans-serif", previewAccent: "#9a2c2c", previewPaper: "#fbfaf8" },
  intercept: { name: "intercept", label: "Intercept", description: "Espionage and political-thriller design with dossier-like labels and crisp institutional hierarchy.", sceneOrnament: "◆", dropcap: false, chapterLabel: "FILE 01", previewFont: "\"Folio Libre Caslon Text\", Georgia, serif", previewHeadingFont: "\"Folio Source Sans 3\", Arial, sans-serif", previewAccent: "#42505c", previewPaper: "#f7f7f4" },
  "black-ice": { name: "black-ice", label: "Black Ice", description: "Nordic-noir minimalism: pale page, narrow titles and cold monochrome structure without decorative noise.", sceneOrnament: "·", dropcap: false, chapterLabel: "01", previewFont: "\"Folio Source Serif 4\", Georgia, serif", previewHeadingFont: "\"Folio Barlow Condensed\", Arial, sans-serif", previewAccent: "#3f4b52", previewPaper: "#f3f5f5" },
  noir: { name: "noir", label: "Noir", description: "Classic crime typography with black-rule chapter cards, elegant contrast and a restrained pulp echo.", sceneOrnament: "◆", dropcap: true, chapterLabel: "CASE I", previewFont: "\"Folio Libre Baskerville\", Georgia, serif", previewHeadingFont: "\"Folio Bodoni Moda\", Georgia, serif", previewAccent: "#232323", previewPaper: "#f7f3eb" },
  dread: { name: "dread", label: "Dread", description: "Modern horror built from silence, oversized numbering and severe negative space rather than gothic ornament.", sceneOrnament: "•", dropcap: false, chapterLabel: "01", previewFont: "\"Folio Source Serif 4\", Georgia, serif", previewHeadingFont: "\"Folio Barlow Condensed\", Arial, sans-serif", previewAccent: "#4b2326", previewPaper: "#f4f1ef" },
  seance: { name: "seance", label: "Séance", description: "Occult horror with ceremonial fine rules, small capitals and an elegant séance-room stillness.", sceneOrnament: "◌", dropcap: true, chapterLabel: "SITTING I", previewFont: "\"Folio EB Garamond\", Georgia, serif", previewHeadingFont: "\"Folio Cinzel\", Georgia, serif", previewAccent: "#59435d", previewPaper: "#f7f1e8" },
  velvet: { name: "velvet", label: "Velvet", description: "Contemporary romance with soft Bodoni italics, graceful whitespace and intimate chapter openings.", sceneOrnament: "❦", dropcap: true, chapterLabel: "Chapter One", previewFont: "\"Folio Libre Baskerville\", Georgia, serif", previewHeadingFont: "\"Folio Bodoni Moda\", Georgia, serif", previewAccent: "#a2546e", previewPaper: "#fff8f7" },
  amour: { name: "amour", label: "Amour", description: "Historical romance with Caslon body text, formal display type and fine ornamental framing.", sceneOrnament: "❧", dropcap: true, chapterLabel: "CHAPTER I", previewFont: "\"Folio Libre Caslon Text\", Georgia, serif", previewHeadingFont: "\"Folio Bodoni Moda\", Georgia, serif", previewAccent: "#8f5d5f", previewPaper: "#fbf4ea" },
  hearth: { name: "hearth", label: "Hearth", description: "Cozy fiction with warm Newsreader text, friendly openings and quiet handmade detail.", sceneOrnament: "✦", dropcap: false, chapterLabel: "Chapter 1", previewFont: "\"Folio Newsreader\", Georgia, serif", previewHeadingFont: "\"Folio Source Serif 4\", Georgia, serif", previewAccent: "#8a623f", previewPaper: "#fff8e9" },
  regency: { name: "regency", label: "Regency", description: "Formal historical fiction with restrained classical rules, small capitals and period-aware proportions.", sceneOrnament: "⁂", dropcap: true, chapterLabel: "CHAPTER I", previewFont: "\"Folio Libre Caslon Text\", Georgia, serif", previewHeadingFont: "\"Folio Cinzel\", Georgia, serif", previewAccent: "#665746", previewPaper: "#faf5e9" },
  voyager: { name: "voyager", label: "Voyager", description: "Adventure fiction with broad directional rules, sturdy typography and energetic chapter architecture.", sceneOrnament: "◇", dropcap: false, chapterLabel: "PASSAGE 01", previewFont: "\"Folio Vollkorn\", Georgia, serif", previewHeadingFont: "\"Folio Barlow Condensed\", Arial, sans-serif", previewAccent: "#35616a", previewPaper: "#f6f3e9" },
  afterglow: { name: "afterglow", label: "Afterglow", description: "YA and contemporary fiction with open spacing, modern sans headings and a light editorial pulse.", sceneOrnament: "✶", dropcap: false, chapterLabel: "01", previewFont: "\"Folio Source Serif 4\", Georgia, serif", previewHeadingFont: "\"Folio Source Sans 3\", Arial, sans-serif", previewAccent: "#a65f6d", previewPaper: "#fffafa" },
  academia: { name: "academia", label: "Academia", description: "Dark-academia and literary mystery styling with Caslon text, classical capitals and library-like discipline.", sceneOrnament: "§", dropcap: true, chapterLabel: "LECTURE I", previewFont: "\"Folio Libre Caslon Text\", Georgia, serif", previewHeadingFont: "\"Folio Cinzel\", Georgia, serif", previewAccent: "#493c32", previewPaper: "#f4efe3" },
  memoir: { name: "memoir", label: "Memoir", description: "Quiet memoir and narrative nonfiction with humane text, clear hierarchy and almost no ornament.", sceneOrnament: "—", dropcap: false, chapterLabel: "1", previewFont: "\"Folio Source Serif 4\", Georgia, serif", previewHeadingFont: "\"Folio Source Sans 3\", Arial, sans-serif", previewAccent: "#4f5d66", previewPaper: "#fbfbf8" },
};

export const SUPPORTED_THEMES = [
  "blackletter", "stanza", "witchlight", "solstice", "literary", "nocturne",
  "obsidian", "grimoire", "ivory", "heritage", "decorative", "cathedral", "aubade",
  "event-horizon", "signal", "nova", "redline", "intercept", "black-ice", "noir",
  "dread", "seance", "velvet", "amour", "hearth", "regency", "voyager",
  "afterglow", "academia", "memoir",
] as const satisfies readonly ThemeName[];

const SUPPORTED_THEME_SET = new Set<string>(SUPPORTED_THEMES);

export function hasTheme(name: string): name is ThemeName { return SUPPORTED_THEME_SET.has(name); }
export function getTheme(name: string): ThemeConfig { return THEMES[hasTheme(name) ? name : "literary"]; }
export function themeList(): ThemeConfig[] { return SUPPORTED_THEMES.map((name) => THEMES[name]); }
