from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def patch(path: str, old: str, new: str, count: int = 1) -> None:
    target = ROOT / path
    value = target.read_text(encoding="utf-8")
    if value.count(old) < count:
        raise RuntimeError(f"expected compositor marker missing in {path}: {old[:120]!r}")
    target.write_text(value.replace(old, new, count), encoding="utf-8")


# Reflow preview. The normal pass remains deliberately strict. The emergency
# pass exists only when strict DP has no complete solution on a narrow viewport;
# even then its caps are far below Chromium's unconstrained justification.
patch(
    "web/src/compositor.ts",
    "  available: number;\n};",
    "  available: number;\n  emergency: boolean;\n};",
)
patch(
    "web/src/compositor.ts",
    "  fontSize: number,\n): LineFit | null {\n  if (gaps <= 0) return null;\n\n  const maxWordSpacing = Math.min(spaceWidth * 0.38, fontSize * 0.115);\n  const minWordSpacing = -Math.min(spaceWidth * 0.14, fontSize * 0.035);\n  const maxTracking = fontSize * 0.0055;\n  const minTracking = -fontSize * 0.0035;",
    "  fontSize: number,\n  emergency = false,\n): LineFit | null {\n  if (gaps <= 0) return null;\n\n  const maxWordSpacing = emergency\n    ? Math.min(spaceWidth * 0.48, fontSize * 0.14)\n    : Math.min(spaceWidth * 0.38, fontSize * 0.115);\n  const minWordSpacing = emergency\n    ? -Math.min(spaceWidth * 0.18, fontSize * 0.045)\n    : -Math.min(spaceWidth * 0.14, fontSize * 0.035);\n  const maxTracking = fontSize * (emergency ? 0.007 : 0.0055);\n  const minTracking = -fontSize * (emergency ? 0.0045 : 0.0035);",
)
patch(
    "web/src/compositor.ts",
    "  fontSize: number,\n): Break[] | null {\n  const count = words.length;",
    "  fontSize: number,\n  emergency = false,\n): Break[] | null {\n  const count = words.length;",
)
patch(
    "web/src/compositor.ts",
    "    available: geometry.width,\n  });",
    "    available: geometry.width,\n    emergency,\n  });",
)
patch(
    "web/src/compositor.ts",
    "          ? fitLine(adjustment, gaps, trackingOps, spaceWidth, fontSize)\n          : null;",
    "          ? fitLine(adjustment, gaps, trackingOps, spaceWidth, fontSize, emergency)\n          : null;",
)
patch(
    "web/src/compositor.ts",
    "            available,\n          });",
    "            available,\n            emergency,\n          });",
)
patch(
    "web/src/compositor.ts",
    "      available: state.available,\n    });",
    "      available: state.available,\n      emergency: state.emergency,\n    });",
)
patch(
    "web/src/compositor.ts",
    "  const breaks = chooseBreaks(words, geometry, spaceWidth, hyphenWidth, fontSize);\n  if (!breaks) {",
    "  let breaks = chooseBreaks(words, geometry, spaceWidth, hyphenWidth, fontSize, false);\n  if (!breaks) breaks = chooseBreaks(words, geometry, spaceWidth, hyphenWidth, fontSize, true);\n  if (!breaks) {",
)
patch(
    "web/src/compositor.ts",
    "    line.className = `folio-composed-line ${lineBreak.justified ? \"folio-line-justified\" : \"folio-line-natural\"}`;",
    "    line.className = `folio-composed-line ${lineBreak.justified ? \"folio-line-justified\" : \"folio-line-natural\"}${lineBreak.emergency ? \" folio-line-emergency\" : \"\"}`;\n    if (lineBreak.emergency) line.dataset.folioEmergency = \"true\";",
)

# Print/PDF mirror. Use the exact same two-pass policy and limits so preview is
# not a flattering mock-up of output generated by a different breaker.
patch(
    "server/pipeline/compositor.ts",
    "      available: number;\n    };",
    "      available: number;\n      emergency: boolean;\n    };",
)
patch(
    "server/pipeline/compositor.ts",
    "      fontSize: number,\n    ): LineFit | null => {\n      if (gaps <= 0) return null;\n      const maxWordSpacing = Math.min(spaceWidth * 0.38, fontSize * 0.115);\n      const minWordSpacing = -Math.min(spaceWidth * 0.14, fontSize * 0.035);\n      const maxTracking = fontSize * 0.0055;\n      const minTracking = -fontSize * 0.0035;",
    "      fontSize: number,\n      emergency = false,\n    ): LineFit | null => {\n      if (gaps <= 0) return null;\n      const maxWordSpacing = emergency\n        ? Math.min(spaceWidth * 0.48, fontSize * 0.14)\n        : Math.min(spaceWidth * 0.38, fontSize * 0.115);\n      const minWordSpacing = emergency\n        ? -Math.min(spaceWidth * 0.18, fontSize * 0.045)\n        : -Math.min(spaceWidth * 0.14, fontSize * 0.035);\n      const maxTracking = fontSize * (emergency ? 0.007 : 0.0055);\n      const minTracking = -fontSize * (emergency ? 0.0045 : 0.0035);",
)

# Wrap the existing server DP in a local two-pass function without duplicating
# its long body. The runner rewrites the state construction/candidate fit to use
# an `emergency` variable, then executes strict first and emergency only if the
# strict pass has no terminal state.
server = ROOT / "server/pipeline/compositor.ts"
s = server.read_text(encoding="utf-8")
start = s.find("      const states: Array<Map<number, State>>")
end_marker = "      const breaks = reversed.reverse();"
end = s.find(end_marker, start)
if start < 0 or end < 0:
    raise RuntimeError("server DP block markers missing")
end += len(end_marker)
block = s[start:end]
block = block.replace(
    "      const states: Array<Map<number, State>>",
    "      const runBreaker = (emergency: boolean): Break[] | null => {\n      const states: Array<Map<number, State>>",
    1,
)
block = block.replace(
    "        available: width,\n      });",
    "        available: width,\n        emergency,\n      });",
    1,
)
block = block.replace(
    "? fitLine(adjustment, gaps, trackingOps, spaceWidth, fontSize)",
    "? fitLine(adjustment, gaps, trackingOps, spaceWidth, fontSize, emergency)",
)
block = block.replace(
    "              available,\n            });",
    "              available,\n              emergency,\n            });",
)
block = block.replace(
    "      if (bestKey < 0) {\n        paragraph.classList.add(\"folio-compositor-safe-fallback\");\n        continue;\n      }",
    "      if (bestKey < 0) return null;",
    1,
)
block = block.replace(
    "          available: state.available,\n        });",
    "          available: state.available,\n          emergency: state.emergency,\n        });",
)
block = block.replace(
    "      const breaks = reversed.reverse();",
    "      return reversed.reverse();\n      };\n\n      const breaks = runBreaker(false) ?? runBreaker(true);\n      if (!breaks) {\n        paragraph.classList.add(\"folio-compositor-safe-fallback\");\n        continue;\n      }",
    1,
)
s = s[:start] + block + s[end:]
s = s.replace(
    '        line.className = `folio-composed-line ${lineBreak.justified ? "folio-line-justified" : "folio-line-natural"}`;',
    '        line.className = `folio-composed-line ${lineBreak.justified ? "folio-line-justified" : "folio-line-natural"}${lineBreak.emergency ? " folio-line-emergency" : ""}`;\n        if (lineBreak.emergency) line.dataset.folioEmergency = "true";',
    1,
)
server.write_text(s, encoding="utf-8")

# Visual QA must reject emergency lines in representative Polish prose. Narrow
# pathological cases may use the bounded emergency pass, but the normal book
# sample is not allowed to depend on it.
visual = ROOT / "scripts/v106-visual-qa.ts"
v = visual.read_text(encoding="utf-8")
v = v.replace(
    "      finalLineNatural: lines.at(-1)?.classList.contains(\"folio-line-natural\") ?? false,",
    "      finalLineNatural: lines.at(-1)?.classList.contains(\"folio-line-natural\") ?? false,\n      emergencyLines: lines.filter((line) => line.dataset.folioEmergency === \"true\").length,",
    1,
)
visual.write_text(v, encoding="utf-8")

print("Folio 1.0.6 bounded emergency composition pass applied")
